DROP TABLE STORE;
DROP TABLE TEMPSTORE;
DROP TABLE SALES;
DROP TABLE TEMPSALES;

CREATE TABLE TEMPSTORE(Store_id int,StoreType char(2),Assortment char(2),CompetitionDistance int,CompetitionOpenSinceMonth smallint, CompetitionOpenSinceYear smallint,
Promo2 tinyint,Promo2SinceWeek smallint,Promo2SineYear smallint,PromoInterval VARCHAR(50)) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INPATH '/user/user01/Project/Input/storewithoutheader.csv' INTO TABLE TEMPSTORE;

CREATE TABLE STORE(STORE_ID INT, COMPETITION_DISTANCE INT, PROMO2 TINYINT, PROMO2SINCEWEEK SMALLINT,PROMO_INTERVAL VARCHAR(50))ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

INSERT OVERWRITE TABLE STORE SELECT Store_id, COMPETITIONDISTANCE , PROMO2, COALESCE(PROMO2SINCEWEEK,0), IF(LENGTH(PROMOINTERVAL)>0,PROMOINTERVAL,'-') FROM TEMPSTORE WHERE STORETYPE='a';

CREATE TABLE TEMPSALES(Store_id INT, DayOfWeek SMALLINT, SALE_DATE DATE, Sales int, Customers int,
Open smallint, Promo tinyint, StateHoliday char(1),SchoolHoliday STRING)  ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' ;

LOAD DATA LOCAL INPATH '/user/user01/Project/Input/sales.csv' INTO TABLE TEMPSALES;

CREATE TABLE SALES(STORE_ID INT, SALE_DATE DATE, SALES INT, PROMO TINYINT, SCHOOL_HOLIDAY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

INSERT OVERWRITE TABLE SALES SELECT A.STORE_ID, A.SALE_DATE, A.SALES , A.PROMO, A.SCHOOLHOLIDAY  FROM TEMPSALES A JOIN STORE B ON A.STORE_ID=B.STORE_ID;
